server:
  port: 9020

spring:
  application:
    name: auth-data-init
  profiles:
    version: 0.0.1-SNAPSHOT
#    active: ${SPRING_PROFILES_ACTIVE:loc}
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://ana-uat.cluster-cftc1rptybbm.rds.cn-north-1.amazonaws.com.cn:5432/anauat
#    username: anauser
#    password: anatestuser

#mybatis:
#  typeAliasesPackage: com.adidas.auth.job.entity
#  mapperLocations: classpath*:/mapper/*.xml

sftp:
   ip: xx.xx.xx.xxx
   username: xx
   password: xxxx

db:
  ip: xx.xx.xx.xxx
  username: xx
  password: xxxx